export type TimerMode =
  'POMODORO' | 'SHORT_BREAK' | 'LONG_BREAK' | 'CUSTOM_STOPWATCH';

export interface StudyRoomSession {
  id: string;
  userId: string;
  deckId?: string; // Optional: Session linked to a specific deck
  mode: TimerMode;
  durationSeconds: number; // Actual time spent focusing
  startedAt: string; // ISO 8601
  completedAt: string; // ISO 8601
  cardsReviewedCount: number;
  createdAt: string;
}

export type QuestType =
  | 'REVIEW_DUE_CARDS' // Auto: Finish SRS due cards
  | 'STUDY_ANY_SET' // Auto: Study any deck in any study mode
  | 'EXPLORE_COMMUNITY_SET' // Auto fallback when 0 SRS due cards
  | 'FOCUS_TIME_TARGET' // Auto: Focus for at least 25 minutes
  | 'FOCUS_45M_TARGET' // Auto: Achieve 45 minutes of total daily focus
  | 'UNBROKEN_POMODORO_25M' // Auto: Complete 1 unbroken 25m Pomodoro session
  | 'PERFECT_TEST_EXAM' // Auto: Complete a test exam with 100% perfect score
  | 'FLAWLESS_SM2_LEARN' // Auto: Complete Learn session without selecting hard/forgot
  | 'CREATE_STUDY_SET' // Auto: Create 1 new study set
  | 'COMPLETE_STUDY_MODE' // Auto: Complete 1 full study session in any mode
  | 'TAKE_PRACTICE_QUIZ' // Auto: Complete 1 quiz
  | 'CUSTOM_USER_TASK'; // Manual: User-added task

export interface DailyQuest {
  id: string;
  userId: string;
  date: string; // YYYY-MM-DD
  type: QuestType;
  title: string;
  targetCount: number; // e.g., 20 cards or 25 minutes
  currentCount: number; // e.g., 12 cards reviewed so far
  isCompleted: boolean;
  actionUrl?: string; // e.g., "/reviews", "/sets/123/learn"
  isAutoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface SRSForecastDay {
  date: string; // YYYY-MM-DD
  dueCardsCount: number;
  isToday: boolean;
}

export interface DayStudySummary {
  date: string; // YYYY-MM-DD
  totalMinutesFocused: number;
  totalCardsReviewed: number;
  streakActive: boolean;
  completionRate: number; // 0.0 to 1.0 (Quests completed / Quests total)
}

export interface StudyRoomDashboardResponse {
  date: string;
  streak: {
    currentStreak: number;
    longestStreak: number;
    hasStudiedToday: boolean;
  };
  todayStats: {
    focusedMinutes: number;
    cardsReviewed: number;
    dailyTargetMinutes: number;
  };
  quests: DailyQuest[];
  srsForecast: SRSForecastDay[];
}
