import mongoose, { Schema, Document } from 'mongoose';
import { DailyQuest, StudyRoomSession } from '../types/studyRoom.types.js';
import { StudySession } from '../types/study.types.js';
import { TestHistory } from '../types/test.types.js';
import { MatchLeaderboardEntry } from '../types/match.types.js';

// 1. DailyQuest Model
export interface DailyQuestDocument extends Omit<DailyQuest, 'id'>, Document {
  id: string;
}

const dailyQuestSchema = new Schema<DailyQuestDocument>(
  {
    id: { type: String, required: true, unique: true, index: true },
    userId: { type: String, required: true, index: true },
    date: { type: String, required: true, index: true },
    type: { type: String, required: true },
    title: { type: String, required: true },
    targetCount: { type: Number, required: true },
    currentCount: { type: Number, default: 0 },
    isCompleted: { type: Boolean, default: false },
    actionUrl: { type: String },
    isAutoGenerated: { type: Boolean, default: true },
  },
  {
    timestamps: true,
    toJSON: {
      transform: (_doc, ret: any) => {
        delete ret._id;
        delete ret.__v;
        return ret;
      },
    },
  }
);
dailyQuestSchema.index({ userId: 1, date: 1 });
export const DailyQuestModel = mongoose.model<DailyQuestDocument>(
  'DailyQuest',
  dailyQuestSchema
);

// 2. StudySession Model
export interface StudySessionDocument
  extends Omit<StudySession, 'id'>, Document {
  id: string;
}

const studySessionSchema = new Schema<StudySessionDocument>(
  {
    id: { type: String, required: true, unique: true, index: true },
    userId: { type: String, required: true, index: true },
    studySetId: { type: String, required: true, index: true },
    mode: { type: String, required: true },
    cardsTotal: { type: Number, default: 0 },
    cardsCorrect: { type: Number, default: 0 },
    cardsIncorrect: { type: Number, default: 0 },
    timeSpentSeconds: { type: Number, default: 0 },
    completedAt: { type: String, required: true },
  },
  {
    timestamps: true,
    toJSON: {
      transform: (_doc, ret: any) => {
        delete ret._id;
        delete ret.__v;
        return ret;
      },
    },
  }
);
export const StudySessionModel = mongoose.model<StudySessionDocument>(
  'StudySession',
  studySessionSchema
);

// 3. StudyRoomSession Model
export interface StudyRoomSessionDocument
  extends Omit<StudyRoomSession, 'id'>, Document {
  id: string;
}

const studyRoomSessionSchema = new Schema<StudyRoomSessionDocument>(
  {
    id: { type: String, required: true, unique: true, index: true },
    userId: { type: String, required: true, index: true },
    deckId: { type: String },
    mode: { type: String, required: true },
    durationSeconds: { type: Number, required: true },
    startedAt: { type: String, required: true },
    completedAt: { type: String, required: true },
    cardsReviewedCount: { type: Number, default: 0 },
  },
  {
    timestamps: true,
    toJSON: {
      transform: (_doc, ret: any) => {
        delete ret._id;
        delete ret.__v;
        return ret;
      },
    },
  }
);
studyRoomSessionSchema.index({ userId: 1, startedAt: 1 });
export const StudyRoomSessionModel = mongoose.model<StudyRoomSessionDocument>(
  'StudyRoomSession',
  studyRoomSessionSchema
);

// 4. TestHistory Model
export interface TestHistoryDocument extends Omit<TestHistory, 'id'>, Document {
  id: string;
}

const testReviewSchema = new Schema(
  {
    questionId: { type: String, required: true },
    cardId: { type: String, required: true },
    prompt: { type: String, required: true },
    type: { type: String, required: true },
    userAnswer: { type: String, default: '' },
    correctAnswer: { type: String, required: true },
    isCorrect: { type: Boolean, default: false },
  },
  { _id: false }
);

const testHistorySchema = new Schema<TestHistoryDocument>(
  {
    id: { type: String, required: true, unique: true, index: true },
    userId: { type: String, required: true, index: true },
    studySetId: { type: String, required: true, index: true },
    scorePercentage: { type: Number, required: true },
    totalQuestions: { type: Number, required: true },
    correctCount: { type: Number, required: true },
    incorrectCount: { type: Number, required: true },
    timeSpentSeconds: { type: Number, default: 0 },
    questionTypes: { type: [String], default: [] },
    reviews: { type: [testReviewSchema], default: [] },
    correctTerms: { type: [String], default: [] },
    incorrectTerms: { type: [String], default: [] },
  },
  {
    timestamps: true,
    toJSON: {
      transform: (_doc, ret: any) => {
        delete ret._id;
        delete ret.__v;
        return ret;
      },
    },
  }
);
export const TestHistoryModel = mongoose.model<TestHistoryDocument>(
  'TestHistory',
  testHistorySchema
);

// 5. MatchLeaderboard Model
export interface MatchLeaderboardDocument
  extends Omit<MatchLeaderboardEntry, 'id'>, Document {
  id: string;
}

const matchLeaderboardSchema = new Schema<MatchLeaderboardDocument>(
  {
    id: { type: String, required: true, unique: true, index: true },
    studySetId: { type: String, required: true, index: true },
    userId: { type: String, required: true, index: true },
    user: {
      id: { type: String, required: true },
      name: { type: String, required: true },
      username: { type: String, required: true },
      avatarUrl: { type: String },
    },
    timeRecordMs: { type: Number, required: true, index: true },
    matchedPairs: { type: Number, required: true },
  },
  {
    timestamps: true,
    toJSON: {
      transform: (_doc, ret: any) => {
        delete ret._id;
        delete ret.__v;
        return ret;
      },
    },
  }
);
matchLeaderboardSchema.index({ studySetId: 1, timeRecordMs: 1 });
export const MatchLeaderboardModel = mongoose.model<MatchLeaderboardDocument>(
  'MatchLeaderboard',
  matchLeaderboardSchema
);
