import { PrivacyLevel } from '../../config/constants.js';
import { StudySet } from '../../types/studySet.types.js';
import { Card } from '../../types/card.types.js';

export const initialStudySetsSeed: StudySet[] = [
  {
    id: 'set_ielts_801',
    title: 'IELTS Band 7.5+ Academic Vocabulary',
    description:
      'Danh sách các từ vựng học thuật đỉnh cao thường gặp trong IELTS Reading & Writing Task 2.',
    privacy: PrivacyLevel.PUBLIC,
    level: 'ADVANCED',
    sourceLanguage: 'en',
    targetLanguage: 'vi',
    creatorId: 'usr_alex_001',
    tags: ['IELTS', 'Academic', 'Writing', 'Reading'],
    viewCount: 1420,
    starredUserIds: ['usr_minh_002'],
    bookmarkedUserIds: ['usr_minh_002'],
    createdAt: '2026-01-15T10:00:00.000Z',
    updatedAt: '2026-01-15T10:00:00.000Z',
  },
  {
    id: 'set_business_802',
    title: 'Essential Business English & Negotiation',
    description:
      'Từ vựng tiếng Anh thương mại chuyên nghiệp dùng trong đàm phán và thuyết trình kinh doanh.',
    privacy: PrivacyLevel.PUBLIC,
    level: 'INTERMEDIATE',
    sourceLanguage: 'en',
    targetLanguage: 'vi',
    creatorId: 'usr_alex_001',
    tags: ['Business', 'Workplace', 'Negotiation', 'Communication'],
    viewCount: 890,
    starredUserIds: [],
    bookmarkedUserIds: [],
    createdAt: '2026-01-20T14:30:00.000Z',
    updatedAt: '2026-01-20T14:30:00.000Z',
  },
  {
    id: 'set_idioms_803',
    title: '50 Common Everyday English Idioms',
    description:
      'Các thành ngữ tiếng Anh tự nhiên thông dụng nhất giúp nâng cao độ trôi chảy khi Speaking.',
    privacy: PrivacyLevel.PUBLIC,
    level: 'BEGINNER',
    sourceLanguage: 'en',
    targetLanguage: 'vi',
    creatorId: 'usr_minh_002',
    tags: ['Idioms', 'Speaking', 'Fluency', 'Daily English'],
    viewCount: 650,
    starredUserIds: ['usr_alex_001'],
    bookmarkedUserIds: ['usr_alex_001'],
    createdAt: '2026-02-05T11:00:00.000Z',
    updatedAt: '2026-02-05T11:00:00.000Z',
  },
  {
    id: 'set_toeic_804',
    title: 'TOEIC 900+ Key Office & Workplace Collocations',
    description:
      'Tuyển tập các cụm từ collocations ăn điểm xuất hiện liên tục trong đề thi TOEIC Listening & Reading part 5, 6, 7.',
    privacy: PrivacyLevel.PUBLIC,
    level: 'INTERMEDIATE',
    sourceLanguage: 'en',
    targetLanguage: 'vi',
    creatorId: 'usr_alex_001',
    tags: ['TOEIC', 'Business', 'Collocations', 'Grammar'],
    viewCount: 1120,
    starredUserIds: ['usr_minh_002', 'usr_sarah_003'],
    bookmarkedUserIds: ['usr_minh_002'],
    createdAt: '2026-02-10T09:15:00.000Z',
    updatedAt: '2026-02-10T09:15:00.000Z',
  },
  {
    id: 'set_oxford_805',
    title: 'Oxford 3000: Core Daily Conversation Words',
    description:
      'Các từ vựng cốt lõi theo khung chuẩn Oxford giúp bạn tự tin giao tiếp tiếng Anh thường ngày.',
    privacy: PrivacyLevel.PUBLIC,
    level: 'BEGINNER',
    sourceLanguage: 'en',
    targetLanguage: 'vi',
    creatorId: 'usr_sarah_003',
    tags: ['Oxford 3000', 'Daily English', 'Speaking', 'Basics'],
    viewCount: 1560,
    starredUserIds: ['usr_alex_001'],
    bookmarkedUserIds: ['usr_alex_001', 'usr_minh_002'],
    createdAt: '2026-02-12T16:00:00.000Z',
    updatedAt: '2026-02-12T16:00:00.000Z',
  },
  {
    id: 'set_phrasal_806',
    title: 'Advanced C1-C2 Phrasal Verbs in Context',
    description:
      'Cụm động từ nâng cao mang tính ứng dụng cao giúp bài nói và viết tự nhiên như người bản xứ.',
    privacy: PrivacyLevel.PUBLIC,
    level: 'ADVANCED',
    sourceLanguage: 'en',
    targetLanguage: 'vi',
    creatorId: 'usr_alex_001',
    tags: ['Phrasal Verbs', 'IELTS', 'Speaking', 'Advanced'],
    viewCount: 980,
    starredUserIds: [],
    bookmarkedUserIds: ['usr_sarah_003'],
    createdAt: '2026-02-18T08:30:00.000Z',
    updatedAt: '2026-02-18T08:30:00.000Z',
  },
  {
    id: 'set_tech_807',
    title: 'Tech & AI Vocabulary for Software Engineers',
    description:
      'Thuật ngữ tiếng Anh chuyên ngành công nghệ thông tin, lập trình và trí tuệ nhân tạo.',
    privacy: PrivacyLevel.PUBLIC,
    level: 'INTERMEDIATE',
    sourceLanguage: 'en',
    targetLanguage: 'vi',
    creatorId: 'usr_minh_002',
    tags: ['Tech', 'Engineering', 'AI', 'Workplace'],
    viewCount: 840,
    starredUserIds: ['usr_alex_001'],
    bookmarkedUserIds: ['usr_alex_001'],
    createdAt: '2026-02-22T13:45:00.000Z',
    updatedAt: '2026-02-22T13:45:00.000Z',
  },
  {
    id: 'set_travel_808',
    title: 'Essential English for Travel & Tourism',
    description:
      'Từ vựng và mẫu câu hữu ích khi đi du lịch nước ngoài: sân bay, khách sạn, nhà hàng và hỏi đường.',
    privacy: PrivacyLevel.PUBLIC,
    level: 'BEGINNER',
    sourceLanguage: 'en',
    targetLanguage: 'vi',
    creatorId: 'usr_sarah_003',
    tags: ['Travel', 'Daily English', 'Speaking', 'Survival'],
    viewCount: 720,
    starredUserIds: [],
    bookmarkedUserIds: [],
    createdAt: '2026-02-25T10:00:00.000Z',
    updatedAt: '2026-02-25T10:00:00.000Z',
  },
];

export const initialCardsSeed: Card[] = [
  // Set 1: IELTS
  {
    id: 'crd_001',
    studySetId: 'set_ielts_801',
    term: 'Ubiquitous',
    definition: 'Phổ biến, có mặt ở khắp mọi nơi cùng lúc',
    phonetic: '/juːˈbɪk.wə.təs/',
    example: 'Smartphones have become ubiquitous in modern urban life.',
    hint: 'Synonym: omnipresent, pervasive',
    orderIndex: 0,
    createdAt: '2026-01-15T10:00:00.000Z',
    updatedAt: '2026-01-15T10:00:00.000Z',
  },
  {
    id: 'crd_002',
    studySetId: 'set_ielts_801',
    term: 'Exacerbate',
    definition: 'Làm trầm trọng thêm, làm xấu đi tình hình',
    phonetic: '/ɪɡˈzæs.ɚ.beɪt/',
    example: 'The recession has exacerbated the problem of youth unemployment.',
    hint: 'Antonym: alleviate, mitigate',
    orderIndex: 1,
    createdAt: '2026-01-15T10:00:00.000Z',
    updatedAt: '2026-01-15T10:00:00.000Z',
  },
  {
    id: 'crd_003',
    studySetId: 'set_ielts_801',
    term: 'Ephemeral',
    definition: 'Phù du, ngắn ngủi, chỉ tồn tại trong thời gian rất ngắn',
    phonetic: '/ɪˈfem.ər.əl/',
    example: 'Fame in the social media era is often ephemeral.',
    hint: 'Synonym: transient, fleeting',
    orderIndex: 2,
    createdAt: '2026-01-15T10:00:00.000Z',
    updatedAt: '2026-01-15T10:00:00.000Z',
  },
  {
    id: 'crd_004',
    studySetId: 'set_ielts_801',
    term: 'Pernicious',
    definition: 'Độc hại, gây nguy hại âm thầm và nghiêm trọng',
    phonetic: '/pɚˈnɪʃ.əs/',
    example: 'The pernicious effects of air pollution are felt over decades.',
    hint: 'Synonym: destructive, harmful',
    orderIndex: 3,
    createdAt: '2026-01-15T10:00:00.000Z',
    updatedAt: '2026-01-15T10:00:00.000Z',
  },
  {
    id: 'crd_005',
    studySetId: 'set_ielts_801',
    term: 'Pragmatic',
    definition: 'Thực tế, thực dụng, dựa trên kết quả cụ thể thay vì lý thuyết',
    phonetic: '/præɡˈmæt̬.ɪk/',
    example: 'We need a pragmatic approach to tackling climate change.',
    hint: 'Synonym: practical, realistic',
    orderIndex: 4,
    createdAt: '2026-01-15T10:00:00.000Z',
    updatedAt: '2026-01-15T10:00:00.000Z',
  },
  {
    id: 'crd_006',
    studySetId: 'set_ielts_801',
    term: 'Meticulous',
    definition: 'Tỉ mỉ, cẩn thận từng chi tiết nhỏ',
    phonetic: '/məˈtɪk.jə.ləs/',
    example:
      'The researcher kept meticulous records of all experimental trials.',
    hint: 'Synonym: thorough, scrupulous',
    orderIndex: 5,
    createdAt: '2026-01-15T10:00:00.000Z',
    updatedAt: '2026-01-15T10:00:00.000Z',
  },

  // Set 2: Business English
  {
    id: 'crd_007',
    studySetId: 'set_business_802',
    term: 'Leverage',
    definition: 'Tận dụng, đòn bẩy để tạo lợi thế cạnh tranh',
    phonetic: '/ˈlev.ɚ.ɪdʒ/',
    example:
      'The startup leveraged AI technology to cut operational costs by 40%.',
    hint: 'Verb & Noun',
    orderIndex: 0,
    createdAt: '2026-01-20T14:30:00.000Z',
    updatedAt: '2026-01-20T14:30:00.000Z',
  },
  {
    id: 'crd_008',
    studySetId: 'set_business_802',
    term: 'Feasibility Study',
    definition: 'Báo cáo / nghiên cứu tính khả thi của một dự án kinh doanh',
    phonetic: '/ˌfiː.zəˈbɪl.ə.t̬i ˈstʌd.i/',
    example:
      'We must conduct a comprehensive feasibility study before expanding overseas.',
    hint: 'Noun phrase',
    orderIndex: 1,
    createdAt: '2026-01-20T14:30:00.000Z',
    updatedAt: '2026-01-20T14:30:00.000Z',
  },
  {
    id: 'crd_009',
    studySetId: 'set_business_802',
    term: 'Stakeholder',
    definition: 'Bên liên quan (khách hàng, cổ đông, nhân viên, đối tác)',
    phonetic: '/ˈsteɪkˌhoʊl.dɚ/',
    example: 'All key stakeholders must approve the budget proposal.',
    hint: 'Corporate term',
    orderIndex: 2,
    createdAt: '2026-01-20T14:30:00.000Z',
    updatedAt: '2026-01-20T14:30:00.000Z',
  },

  // Set 3: Idioms
  {
    id: 'crd_010',
    studySetId: 'set_idioms_803',
    term: 'Bite the bullet',
    definition: 'Cắn răng chịu đựng, chấp nhận đối mặt với tình huống khó khăn',
    phonetic: '/baɪt ðə ˈbʊl.ɪt/',
    example: 'I hate dentists, but I just had to bite the bullet and go.',
    hint: 'Originated from battlefield surgery',
    orderIndex: 0,
    createdAt: '2026-02-05T11:00:00.000Z',
    updatedAt: '2026-02-05T11:00:00.000Z',
  },
  {
    id: 'crd_011',
    studySetId: 'set_idioms_803',
    term: 'Hit the nail on the head',
    definition: 'Nói chính xác điểm cốt lõi, trúng tim đen',
    phonetic: '/hɪt ðə neɪl ɒn ðə hed/',
    example:
      'You hit the nail on the head when you said communication was our biggest issue.',
    hint: 'Exact accuracy',
    orderIndex: 1,
    createdAt: '2026-02-05T11:00:00.000Z',
    updatedAt: '2026-02-05T11:00:00.000Z',
  },
  {
    id: 'crd_012',
    studySetId: 'set_idioms_803',
    term: 'Under the weather',
    definition: 'Cảm thấy hơi mệt hoặc không khỏe trong người',
    phonetic: '/ˈʌn.dɚ ðə ˈweð.ɚ/',
    example:
      'I was feeling a bit under the weather so I stayed home from work.',
    hint: 'Slightly unwell',
    orderIndex: 2,
    createdAt: '2026-02-05T11:00:00.000Z',
    updatedAt: '2026-02-05T11:00:00.000Z',
  },

  // Set 4: TOEIC Collocations
  {
    id: 'crd_013',
    studySetId: 'set_toeic_804',
    term: 'Meet the deadline',
    definition: 'Kịp hạn chót, hoàn thành đúng thời hạn',
    phonetic: '/miːt ðə ˈded.laɪn/',
    example: 'Our team worked extra hours to meet the project deadline.',
    hint: 'Verb phrase',
    orderIndex: 0,
    createdAt: '2026-02-10T09:15:00.000Z',
    updatedAt: '2026-02-10T09:15:00.000Z',
  },
  {
    id: 'crd_014',
    studySetId: 'set_toeic_804',
    term: 'Address concerns',
    definition: 'Giải quyết các thắc mắc, băn khoăn của khách hàng',
    phonetic: '/əˈdres kənˈsɝːnz/',
    example: 'The manager held a meeting to address employees’ concerns.',
    hint: 'Professional phrase',
    orderIndex: 1,
    createdAt: '2026-02-10T09:15:00.000Z',
    updatedAt: '2026-02-10T09:15:00.000Z',
  },
  {
    id: 'crd_015',
    studySetId: 'set_toeic_804',
    term: 'In accordance with',
    definition: 'Phù hợp với, tuân theo quy định / chính sách',
    phonetic: '/ɪn əˈkɔːr.dəns wɪð/',
    example: 'All procedures were carried out in accordance with state laws.',
    hint: 'Formal prepositional phrase',
    orderIndex: 2,
    createdAt: '2026-02-10T09:15:00.000Z',
    updatedAt: '2026-02-10T09:15:00.000Z',
  },

  // Set 5: Oxford 3000
  {
    id: 'crd_016',
    studySetId: 'set_oxford_805',
    term: 'Accomplish',
    definition: 'Đạt được, hoàn thành một mục tiêu xác định',
    phonetic: '/əˈkɑːm.plɪʃ/',
    example: 'You can accomplish anything with dedication and consistency.',
    hint: 'Synonym: achieve, fulfill',
    orderIndex: 0,
    createdAt: '2026-02-12T16:00:00.000Z',
    updatedAt: '2026-02-12T16:00:00.000Z',
  },
  {
    id: 'crd_017',
    studySetId: 'set_oxford_805',
    term: 'Genuine',
    definition: 'Chân thật, thành thật, chính hãng',
    phonetic: '/ˈdʒen.ju.ɪn/',
    example:
      'She showed genuine interest in learning about Vietnamese culture.',
    hint: 'Synonym: authentic, sincere',
    orderIndex: 1,
    createdAt: '2026-02-12T16:00:00.000Z',
    updatedAt: '2026-02-12T16:00:00.000Z',
  },
  {
    id: 'crd_018',
    studySetId: 'set_oxford_805',
    term: 'Significant',
    definition: 'Quan trọng, có ý nghĩa lớn, đáng kể',
    phonetic: '/sɪɡˈnɪf.ə.kənt/',
    example: 'There was a significant improvement in student test scores.',
    hint: 'Synonym: important, notable',
    orderIndex: 2,
    createdAt: '2026-02-12T16:00:00.000Z',
    updatedAt: '2026-02-12T16:00:00.000Z',
  },

  // Set 6: Phrasal Verbs
  {
    id: 'crd_019',
    studySetId: 'set_phrasal_806',
    term: 'Brush up on',
    definition: 'Ôn tập, trau dồi lại kiến thức đã lâu không dùng',
    phonetic: '/brʌʃ ʌp ɒn/',
    example: 'I need to brush up on my Spanish before my trip to Madrid.',
    hint: 'Review or refresh skill',
    orderIndex: 0,
    createdAt: '2026-02-18T08:30:00.000Z',
    updatedAt: '2026-02-18T08:30:00.000Z',
  },
  {
    id: 'crd_020',
    studySetId: 'set_phrasal_806',
    term: 'Come up with',
    definition: 'Nảy ra, sáng kiến ra một ý tưởng hoặc giải pháp',
    phonetic: '/kʌm ʌp wɪð/',
    example: 'She came up with a brilliant idea for the marketing campaign.',
    hint: 'Produce an idea',
    orderIndex: 1,
    createdAt: '2026-02-18T08:30:00.000Z',
    updatedAt: '2026-02-18T08:30:00.000Z',
  },

  // Set 7: Tech & AI
  {
    id: 'crd_021',
    studySetId: 'set_tech_807',
    term: 'Scalability',
    definition: 'Khả năng mở rộng của hệ thống phần mềm khi tải lượng tăng',
    phonetic: '/ˌskeɪ.ləˈbɪl.ə.t̬i/',
    example: 'Cloud architecture ensures high scalability during peak traffic.',
    hint: 'System capacity to grow',
    orderIndex: 0,
    createdAt: '2026-02-22T13:45:00.000Z',
    updatedAt: '2026-02-22T13:45:00.000Z',
  },
  {
    id: 'crd_022',
    studySetId: 'set_tech_807',
    term: 'Inference',
    definition:
      'Quá trình suy luận / dự đoán của mô hình AI khi nhận dữ liệu mới',
    phonetic: '/ˈɪn.fɚ.əns/',
    example:
      'Optimizing model weights reduces latency during real-time inference.',
    hint: 'Machine learning term',
    orderIndex: 1,
    createdAt: '2026-02-22T13:45:00.000Z',
    updatedAt: '2026-02-22T13:45:00.000Z',
  },

  // Set 8: Travel English
  {
    id: 'crd_023',
    studySetId: 'set_travel_808',
    term: 'Boarding Pass',
    definition: 'Thẻ lên máy bay',
    phonetic: '/ˈbɔːr.dɪŋ ˌpæs/',
    example: 'Please have your passport and boarding pass ready at the gate.',
    hint: 'Airport travel essential',
    orderIndex: 0,
    createdAt: '2026-02-25T10:00:00.000Z',
    updatedAt: '2026-02-25T10:00:00.000Z',
  },
  {
    id: 'crd_024',
    studySetId: 'set_travel_808',
    term: 'Complimentary',
    definition: 'Miễn phí kèm theo dịch vụ (khách sạn, máy bay)',
    phonetic: '/ˌkɑːm.pləˈmen.tər.i/',
    example:
      'The hotel provides a complimentary breakfast buffet every morning.',
    hint: 'Free of charge',
    orderIndex: 1,
    createdAt: '2026-02-25T10:00:00.000Z',
    updatedAt: '2026-02-25T10:00:00.000Z',
  },
];
